apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pizza-app
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "tmp/data"