# Generated by Django 5.1.1 on 2024-09-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=50)),
                ('sinstructions', models.CharField(max_length=100)),
                ('pizza_flavor', models.CharField(choices=[('PP', 'Pepperoni'), ('SP', 'Supreme'), ('CH', 'Chicago')], default='PP', max_length=2)),
            ],
        ),
    ]
